### ISSUE TITLE
Tests fail since Mojolicious 7.38 or 7.39

### ISSUE THREAD

**Issue by eserte** [jhthorsen/cloudinary#2] opened 2017-08-16 10:15 UTC
I see the following new failure on my smokers:
```
Unmatched [ in regex; marked by <-- HERE in m/([ <-- HERE ^A-Za-z0-9\-._~\\/ at (eval 82) line 1.
 at /home/cpansand/.cpan/build/2017081612/Cloudinary-0.15-eIh5C8/blib/lib/Cloudinary.pm line 137.
t/cloudinary.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
...
Unmatched [ in regex; marked by <-- HERE in m/([ <-- HERE ^A-Za-z0-9\-._~\\/ at (eval 82) line 1.
 at /home/cpansand/.cpan/build/2017081612/Cloudinary-0.15-eIh5C8/blib/lib/Cloudinary.pm line 137.
t/simple.t ...... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
```

Statistical analysis suggests that the failure was caused by recent Mojolicious versions:
```
****************************************************************
Regression 'mod:Mojolicious'
****************************************************************
Name           	       Theta	      StdErr	 T-stat
[0='const']    	      1.0000	      0.0000	9159260074760476.00
[1='eq_6.60']  	      0.0000	      0.0000	   0.99
[2='eq_6.62']  	      0.0000	      0.0000	   0.52
[3='eq_6.63']  	      0.0000	      0.0000	   0.49
[4='eq_6.64']  	      0.0000	      0.0000	   1.69
[5='eq_6.66']  	      0.0000	      0.0000	   1.59
[6='eq_7.0']   	      0.0000	      0.0000	   1.76
[7='eq_7.03']  	      0.0000	      0.0000	   0.24
[8='eq_7.07']  	      0.0000	      0.0000	   1.62
[9='eq_7.08']  	     -0.0000	      0.0000	  -1.04
[10='eq_7.09'] 	      0.0000	      0.0000	   0.18
[11='eq_7.10'] 	      0.0000	      0.0000	   2.16
[12='eq_7.12'] 	      0.0000	      0.0000	   1.08
[13='eq_7.14'] 	      0.0000	      0.0000	   0.42
[14='eq_7.18'] 	      0.0000	      0.0000	   1.80
[15='eq_7.20'] 	     -0.0000	      0.0000	  -0.72
[16='eq_7.21'] 	      0.0000	      0.0000	   2.64
[17='eq_7.26'] 	      0.0000	      0.0000	   1.08
[18='eq_7.28'] 	     -0.0000	      0.0000	  -2.91
[19='eq_7.30'] 	      0.0000	      0.0000	   4.09
[20='eq_7.31'] 	      0.0000	      0.0000	   1.86
[21='eq_7.33'] 	      0.0000	      0.0000	   2.78
[22='eq_7.35'] 	      0.0000	      0.0000	   2.49
[23='eq_7.36'] 	      0.0000	      0.0000	   1.82
[24='eq_7.37'] 	      0.0000	      0.0000	   1.80
[25='eq_7.39'] 	     -1.0000	      0.0000	-8689237055426159.00
[26='eq_7.40'] 	     -1.0000	      0.0000	-8567703279027793.00
[27='eq_7.41'] 	     -1.0000	      0.0000	-8826083852998761.00

R^2= 1.000, N= 109, K= 28
****************************************************************
```

(@kraih: FYI; actually I did not see a documented change in 7.38 or 7.39 which matches the test failures)

**Comment by evoyy** [comment] 2017-12-18 02:25
This seems to be caused by a bug in Mojo::Util::url_escape. I have created this issue: https://github.com/kraih/mojo/issues/1169

**Comment by evoyy** [comment] 2018-01-14 01:13
This issue can be closed. Resolved by https://github.com/jhthorsen/cloudinary/pull/5

**Comment by jhthorsen** [comment] 2018-01-14 18:59
👍

**Closed by jhthorsen** 2018-01-14 18:59 UTC
Labels: bug
